services:
  ownfolio:
    build: .
    ports:
      - 3000:3000
    environment:
      PGHOST: postgres
      PGDATABASE: ownfolio
      PGUSER: ownfolio
      PGPASSWORD: ownfolio
    restart: always
    depends_on:
      - postgres
  postgres:
    image: postgres:15
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ownfolio
      POSTGRES_USER: ownfolio
      POSTGRES_PASSWORD: ownfolio
    restart: always
